# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37d53476bbaf062fc0dc53b5436e141b41c5cafab4b52897dba85d74fff9335cf7cefb2739ee60f299679fe3778b0acfc3499a2309316c0952b43003ab170dc4

test:
  secret_key_base: 238c2ff269399bf06d9e38be8bf48586b30f453cb1b2dffee525cf4e4e394f95ab33cb0b749a0e4de48e97a6cb412f0b78a8cfa495c185144d8bbe95d0008e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
